### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AceTTV** [3SnipeTeam/3Snipe#3]
i get this when runing the bat file
 C:\Users\Explo\Desktop\3Snipe-master\node_modules\raw-socket>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.

**Comment by lolwhenlifegivesyoulemons** [comment]
Closed. 3Snipe-JS is currently broken at the moment. Sorry!

**Comment by AceTTV** [comment]
thank you for helping please pm me on discord (PHOT0#7015) when it is fixed
